/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
export const PATH_PERMISSION_MAP: Record<string, string> = {
  '/': 'MENU_HOME_VIEW',
  '/home': 'MENU_HOME_VIEW',
  '/company': 'MENU_HOME_VIEW',
  '/reports': 'MENU_HOME_VIEW',
  '/reports/cashflow-forecast': 'MENU_HOME_VIEW',
  '/reports/vendor-performance': 'MENU_HOME_VIEW',
  '/reports/trial-balance': 'MENU_HOME_VIEW',
  '/customers': 'MENU_CUSTOMERS_VIEW',
  '/customers/create': 'MENU_CUSTOMERS_CREATE',
  '/crm': 'MENU_HOME_VIEW',
  '/crm/pipeline': 'MENU_HOME_VIEW',
  '/crm/opportunities': 'MENU_HOME_VIEW',
  '/crm/opportunities/new': 'MENU_HOME_VIEW',
  '/crm/opportunities/:id': 'MENU_HOME_VIEW',
  '/crm/opportunities/:id/edit': 'MENU_HOME_VIEW',
  '/suppliers': 'MENU_SUPPLIERS_VIEW',
  '/suppliers/create': 'MENU_SUPPLIERS_CREATE',
  '/users': 'MENU_USERS_VIEW',
  '/users/create': 'MENU_USERS_CREATE',
  '/products': 'MENU_PRODUCTS_VIEW',
  '/products/create': 'MENU_PRODUCTS_CREATE',
  '/features': 'MENU_FEATURES_VIEW',
  '/features/create': 'MENU_FEATURES_CREATE',
  '/category': 'MENU_CATEGORIES_VIEW',
  '/category/create': 'MENU_CATEGORIES_CREATE',
  '/orders': 'MENU_ORDERS_VIEW',
  '/orders/create': 'MENU_ORDERS_CREATE',
  '/returns': 'MENU_ORDERS_VIEW',
  '/returns/find': 'MENU_ORDERS_VIEW',
  '/returns/create': 'MENU_ORDERS_CREATE',
  '/quotes': 'MENU_SALES_QUOTES_VIEW',
  '/quotes/create': 'MENU_SALES_QUOTES_CREATE',
  '/pos': 'MENU_PURCHASE_ORDERS_VIEW',
  '/pos/create': 'MENU_PURCHASE_ORDERS_CREATE',
  '/transfers': 'MENU_TRANSFER_ORDERS_VIEW',
  '/transfers/create': 'MENU_TRANSFER_ORDERS_CREATE',
  '/pos/quotes': 'MENU_PURCHASE_ORDERS_VIEW',
  '/pos/quotes/create': 'MENU_PURCHASE_ORDERS_CREATE',
  '/shipments': 'MENU_SHIPMENTS_VIEW',
  '/shipments/create': 'MENU_SHIPMENTS_CREATE',
  '/invoices': 'MENU_INVOICES_VIEW',
  '/invoices/sales': 'MENU_INVOICES_VIEW',
  '/invoices/purchase': 'MENU_INVOICES_VIEW',
  '/finance': 'MENU_HOME_VIEW',
  '/finance/chart-of-accounts': 'MENU_HOME_VIEW',
  '/finance/journal-entries': 'MENU_HOME_VIEW',
  '/finance/exchange-rates': 'MENU_HOME_VIEW',
  '/finance/trial-balance': 'MENU_HOME_VIEW',
  '/payments': 'MENU_INVOICES_VIEW',
  '/assets': 'MENU_ASSETS_VIEW',
  '/assets/create': 'MENU_ASSETS_CREATE',
  '/assets/move': 'MENU_ASSETS_CREATE',
  '/assets/inspection': 'MENU_ASSETS_VIEW',
  '/fixed-assets': 'MENU_ASSETS_VIEW',
  '/fixed-assets/new': 'MENU_ASSETS_CREATE',
  '/fixed-assets/:id': 'MENU_ASSETS_VIEW',
  '/fixed-assets/:id/edit': 'MENU_ASSETS_CREATE',
  '/facilities': 'MENU_FACILITIES_VIEW',
  '/facilities/create': 'MENU_FACILITIES_CREATE',
  '/jobs': 'MENU_JOBS_VIEW',
  '/jobs/create': 'MENU_JOBS_CREATE',
  '/boms': 'MENU_BOMS_VIEW',
  '/boms/create': 'MENU_BOMS_CREATE',
  '/routings': 'MENU_ROUTINGS_VIEW',
  '/routings/create': 'MENU_ROUTINGS_CREATE',
  '/operations': 'MENU_OPERATIONS_VIEW',
  '/operations/create': 'MENU_OPERATIONS_CREATE',
  '/lots': 'MENU_LOTS_VIEW',
  '/lots/create': 'MENU_LOTS_CREATE',
  '/picklists': 'MENU_PICKLISTS_VIEW',
  '/picklists/packing-station': 'MENU_PICKLISTS_VIEW',
  '/picklists/create': 'MENU_PICKLISTS_CREATE',
  '/cycle-count': 'MENU_CYCLE_COUNT_VIEW',
  '/cycle-count/create': 'MENU_CYCLE_COUNT_VIEW',
  '/cycle-count/find': 'MENU_CYCLE_COUNT_VIEW',
  '/replenishment': 'MENU_REPLENISHMENT_VIEW',
  '/requirements': 'MENU_REQUIREMENTS_VIEW',
  '/requirements/create': 'MENU_REQUIREMENTS_CREATE',
  '/timesheets': 'MENU_HOME_VIEW',
  '/timesheets/create': 'MENU_HOME_VIEW',
  '/timesheets/:id': 'MENU_HOME_VIEW',
  '/timesheets/:id/edit': 'MENU_HOME_VIEW',
  '/projects': 'MENU_HOME_VIEW',
  '/projects/new': 'MENU_HOME_VIEW',
  '/projects/planning': 'MENU_HOME_VIEW',
  '/projects/:id': 'MENU_HOME_VIEW',
  '/projects/:id/edit': 'MENU_HOME_VIEW',
  '/data-exchange': 'MENU_DATA_EXCHANGE_VIEW',
  '/async-services': 'MENU_DATA_EXCHANGE_VIEW',
  '/support': 'MENU_HOME_VIEW',
  '/support/tickets': 'MENU_HOME_VIEW',
  '/support/submit': 'MENU_HOME_VIEW',
  '/support/admin': 'SUPER_ADMIN_ONLY',
  '/system': 'SUPER_ADMIN_ONLY',
  '/system/audit-log': 'SUPER_ADMIN_ONLY',
};
